services:
  app:
    image: ivalexandr/memes-bot:latest
    container_name: memes-bot
    ports:
      - '3001:3001'
    volumes:
      - ./data:/app/dist/memes
      - ./data:/app/dist/database/db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - OWNER_ID=${OWNER_ID}
      - DEEPSEEK_TOKEN=${DEEPSEEK_TOKEN}
      - DEEPSEEK_URL=${DEEPSEEK_URL}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
      - CONTEXT_TTL_HOURS=${CONTEXT_TTL_HOURS}
      - CONTEXT_MAX_TURNS=${CONTEXT_MAX_TURNS}
      - EXCLUDE_USER_FOR_KEYWORDS=${EXCLUDE_USER_FOR_KEYWORDS}
    restart: unless-stopped
