// ⚠️ THIS FILE IS AUTO-GENERATED. DO NOT EDIT BY HAND.
export const TYPES = {
  AddAction: Symbol.for('AddAction'),
  AiChatAction: Symbol.for('AiChatAction'),
  AssignAction: Symbol.for('AssignAction'),
  BackgroundCleanupCronService: Symbol.for('BackgroundCleanupCronService'),
  BotMessageRepository: Symbol.for('BotMessageRepository'),
  BotService: Symbol.for('BotService'),
  CommandMenuService: Symbol.for('CommandMenuService'),
  ConversationRepository: Symbol.for('ConversationRepository'),
  DatabaseService: Symbol.for('DatabaseService'),
  GetAction: Symbol.for('GetAction'),
  HelpAction: Symbol.for('HelpAction'),
  JokeAction: Symbol.for('JokeAction'),
  KeywordAction: Symbol.for('KeywordAction'),
  LlmService: Symbol.for('LlmService'),
  LoggerService: Symbol.for('LoggerService'),
  MemesRepository: Symbol.for('MemesRepository'),
  RandomReactionsAction: Symbol.for('RandomReactionsAction'),
  StartAction: Symbol.for('StartAction'),
  UserRepository: Symbol.for('UserRepository'),
} as const;
