name: Build & Push

on:
  push:
    branches: [trunk]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/memes-bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build & push :latest
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
