name: Build and Deploy to VPS

on:
  push:
    branches: [main]

env:
  VPS_IP: ${{ secrets.VPS_IP }}
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
  DOCKER_IMAGE: memes-bot
  DOCKER_COMPOSE_FILE: docker-compose.prod.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/$DOCKER_IMAGE:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$DOCKER_IMAGE:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/$DOCKER_IMAGE:latest
            docker-compose -f $DOCKER_COMPOSE_FILE down
            docker-compose -f $DOCKER_COMPOSE_FILE up -d
